// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/kostaspt/domane/api/config"
	"github.com/kostaspt/domane/api/internal/net/rest"
	"github.com/kostaspt/domane/api/internal/net/server"
	"github.com/kostaspt/domane/api/internal/net/ws"
)

// Injectors from wire.go:

func initApp(contextContext context.Context, configConfig *config.Config) (*kratos.App, func(), error) {
	handler := rest.NewHandler(configConfig)
	wsHandler := ws.NewHandler(configConfig)
	httpServer := server.NewServer(configConfig, handler, wsHandler)
	app := newApp(httpServer)
	return app, func() {
	}, nil
}
